#include "modules.hpp"

#include "int/int.cpp"
#include "tim/tim.cpp"
#include "spu/spu.cpp"
#include "gpu/gpu.cpp"
#include "mem/mem.cpp"
#include "key/key.cpp"
#include "sram/sram.cpp"
#include "regionhandler/regionhandler.cpp"
#include "sys/sys.cpp"
