#ifndef LINKMODE_HPP
#define LINKMODE_HPP

#include "../agb.h"

enum E_LINKMODE_CONTROLS { 
	CONTROL_LINKMODE_MENU2,			
	CONTROL_LINKMODE_MODE,			
	CONTROL_LINKMODE_MASTER,			
	CONTROL_LINKMODE_SYNCRATE,
	CONTROL_LINKMODE_SYNCTICKS,		
	CONTROL_LINKMODE_RECEIVE,		
	CONTROL_LINKMODE_SEND,				
	CONTROL_LINKMODE_COUNT,
	CONTROL_LINKMODE_MAX
};

class LinkMode {
	public:
		
};


#endif

