#ifndef PERFORMANCE_HPP
#define PERFORMANCE_HPP

#include "../../agb.h"

#include "../../data/control.hpp"
#include "../../data/display.hpp"
#include "../../kernel/regionhandler/regionhandler.hpp"

enum E_LIVE1_CONTROLS { 
	CONTROL_LIVE1_RETRIG,			CONTROL_LIVE1_SPEED,			CONTROL_LIVE1_QUANTIZE1,
	CONTROL_LIVE1_VAL_LEFT_00,		CONTROL_LIVE1_VAL_LEFT_01,		CONTROL_LIVE1_VAL_LEFT_02,		CONTROL_LIVE1_VAL_LEFT_03,
	CONTROL_LIVE1_VAL_LEFT_04,		CONTROL_LIVE1_VAL_LEFT_05,		CONTROL_LIVE1_VAL_LEFT_06,		CONTROL_LIVE1_VAL_LEFT_07,
	CONTROL_LIVE1_VOL_LEFT_00,		CONTROL_LIVE1_VOL_LEFT_01,		CONTROL_LIVE1_VOL_LEFT_02,		CONTROL_LIVE1_VOL_LEFT_03,
	CONTROL_LIVE1_VOL_LEFT_04,		CONTROL_LIVE1_VOL_LEFT_05,		CONTROL_LIVE1_VOL_LEFT_06,		CONTROL_LIVE1_VOL_LEFT_07,
	CONTROL_LIVE1_INS_LEFT_00,		CONTROL_LIVE1_INS_LEFT_01,		CONTROL_LIVE1_INS_LEFT_02,		CONTROL_LIVE1_INS_LEFT_03,
	CONTROL_LIVE1_INS_LEFT_04,		CONTROL_LIVE1_INS_LEFT_05,		CONTROL_LIVE1_INS_LEFT_06,		CONTROL_LIVE1_INS_LEFT_07,
	CONTROL_LIVE1_CHAN_LEFT_00,		CONTROL_LIVE1_CHAN_LEFT_01,		CONTROL_LIVE1_CHAN_LEFT_02,		CONTROL_LIVE1_CHAN_LEFT_03,
	CONTROL_LIVE1_CHAN_LEFT_04,		CONTROL_LIVE1_CHAN_LEFT_05,		CONTROL_LIVE1_CHAN_LEFT_06,		CONTROL_LIVE1_CHAN_LEFT_07,
	CONTROL_LIVE1_KEY_LEFT_00,		CONTROL_LIVE1_KEY_LEFT_01,		CONTROL_LIVE1_KEY_LEFT_02,		CONTROL_LIVE1_KEY_LEFT_03,
	CONTROL_LIVE1_KEY_LEFT_04,		CONTROL_LIVE1_KEY_LEFT_05,		CONTROL_LIVE1_KEY_LEFT_06,		CONTROL_LIVE1_KEY_LEFT_07,
	CONTROL_LIVE1_CMD_LEFT_00,		CONTROL_LIVE1_CMD_LEFT_01,		CONTROL_LIVE1_CMD_LEFT_02,		CONTROL_LIVE1_CMD_LEFT_03,
	CONTROL_LIVE1_CMD_LEFT_04,		CONTROL_LIVE1_CMD_LEFT_05,		CONTROL_LIVE1_CMD_LEFT_06,		CONTROL_LIVE1_CMD_LEFT_07,
	CONTROL_LIVE1_VAL_RIGHT_00,		CONTROL_LIVE1_VAL_RIGHT_01,		CONTROL_LIVE1_VAL_RIGHT_02,		CONTROL_LIVE1_VAL_RIGHT_03,
	CONTROL_LIVE1_VAL_RIGHT_04,		CONTROL_LIVE1_VAL_RIGHT_05,		CONTROL_LIVE1_VAL_RIGHT_06,		CONTROL_LIVE1_VAL_RIGHT_07,
	CONTROL_LIVE1_CMD_RIGHT_00,		CONTROL_LIVE1_CMD_RIGHT_01,		CONTROL_LIVE1_CMD_RIGHT_02,		CONTROL_LIVE1_CMD_RIGHT_03,
	CONTROL_LIVE1_CMD_RIGHT_04,		CONTROL_LIVE1_CMD_RIGHT_05,		CONTROL_LIVE1_CMD_RIGHT_06,		CONTROL_LIVE1_CMD_RIGHT_07,
	CONTROL_LIVE1_CHAN_RIGHT_00,	CONTROL_LIVE1_CHAN_RIGHT_01,	CONTROL_LIVE1_CHAN_RIGHT_02,	CONTROL_LIVE1_CHAN_RIGHT_03,
	CONTROL_LIVE1_CHAN_RIGHT_04,	CONTROL_LIVE1_CHAN_RIGHT_05,	CONTROL_LIVE1_CHAN_RIGHT_06,	CONTROL_LIVE1_CHAN_RIGHT_07,
	CONTROL_LIVE1_INS_RIGHT_00,		CONTROL_LIVE1_INS_RIGHT_01,		CONTROL_LIVE1_INS_RIGHT_02,		CONTROL_LIVE1_INS_RIGHT_03,
	CONTROL_LIVE1_INS_RIGHT_04,		CONTROL_LIVE1_INS_RIGHT_05,		CONTROL_LIVE1_INS_RIGHT_06,		CONTROL_LIVE1_INS_RIGHT_07,
	CONTROL_LIVE1_VOL_RIGHT_00,		CONTROL_LIVE1_VOL_RIGHT_01,		CONTROL_LIVE1_VOL_RIGHT_02,		CONTROL_LIVE1_VOL_RIGHT_03,
	CONTROL_LIVE1_VOL_RIGHT_04,		CONTROL_LIVE1_VOL_RIGHT_05,		CONTROL_LIVE1_VOL_RIGHT_06,		CONTROL_LIVE1_VOL_RIGHT_07,
	CONTROL_LIVE1_KEY_RIGHT_00,		CONTROL_LIVE1_KEY_RIGHT_01,		CONTROL_LIVE1_KEY_RIGHT_02,		CONTROL_LIVE1_KEY_RIGHT_03,
	CONTROL_LIVE1_KEY_RIGHT_04,		CONTROL_LIVE1_KEY_RIGHT_05,		CONTROL_LIVE1_KEY_RIGHT_06,		CONTROL_LIVE1_KEY_RIGHT_07,
	CONTROL_LIVE1_COUNT,			CONTROL_LIVE1_MAX 
};

enum E_LIVE1_DISPLAYS { 
	LIVE1_DISPLAY_STATUS_LOCKED,
	LIVE1_DISPLAY_STATUS_FREE,
	LIVE1_DISPLAY_SELECT,
	LIVE1_DISPLAY_START,
	LIVE1_DISPLAY_RIGHT_A,
	LIVE1_DISPLAY_LEFT_A,
	LIVE1_DISPLAY_RIGHT_B,
	LIVE1_DISPLAY_LEFT_B,
	
	LIVE1_DISPLAY_RIGHT_UP,
	LIVE1_DISPLAY_LEFT_UP,
	LIVE1_DISPLAY_RIGHT_RIGHT,
	LIVE1_DISPLAY_LEFT_RIGHT,
	LIVE1_DISPLAY_RIGHT_DOWN,
	LIVE1_DISPLAY_LEFT_DOWN,
	LIVE1_DISPLAY_RIGHT_LEFT,
	LIVE1_DISPLAY_LEFT_LEFT,
	
	LIVE1_DISPLAY_RIGHT_L,
	LIVE1_DISPLAY_LEFT_L,
	LIVE1_DISPLAY_RIGHT_R,
	LIVE1_DISPLAY_LEFT_R,
	LIVE1_DISPLAY_COUNT,
	LIVE1_DISPLAY_MAX 
};

#define LIVE_TABLE_LENGTH 		8
#define LIVE_TABLE_SIZE			((6*LIVE_TABLE_LENGTH)*2)

typedef struct sLiveTable {
	u8		KEY			[ LIVE_TABLE_LENGTH ];/*7*/
	u8		INS			[ LIVE_TABLE_LENGTH ];/*6*/
	u8		CHAN		[ LIVE_TABLE_LENGTH ];/*3*/
	u8		VOL			[ LIVE_TABLE_LENGTH ];/*4*/
	u8		CMD			[ LIVE_TABLE_LENGTH ];/*5*/
	u8		VAL			[ LIVE_TABLE_LENGTH ];/*8*/
} LiveTable;

class Performance{
	public:
		MEM_IN_EWRAM static LiveTable	LEFT;
		MEM_IN_EWRAM static LiveTable	RIGHT;
		MEM_IN_EWRAM static u8 			RETRIG;
		MEM_IN_EWRAM static u8 			SPEED /*4*/;
		MEM_IN_EWRAM static u8	 		QUANTIZE /*3*/;
		MEM_IN_EWRAM static u8			LOCK;
		MEM_IN_EWRAM static u8 			vars[ CONTROL_LIVE1_MAX ];	
		

		static void update	( );
		
		static void seek	( );
		static void clear	( );
		static void write	( );
		static void read	( );

		static void dispatchMessage	( u32 msg, u32 pointer=0 );
};

extern const Control LIVE1_CONTROLS[ CONTROL_LIVE1_MAX ];
extern const Display LIVE1_DISPLAYS[ LIVE1_DISPLAY_MAX ];

#endif 
